<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Project Euler</title>
</head>
<body>
	<h1>Task1</h1>
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
Find the sum of all the multiples of 3 or 5 below 1000.
<br/>

<?php
$firsNmbr = 3;
$secondNmbr = 5;
$endIndex = 1000;
$numbers = array();
for ($index = 1; $index <= $endIndex; $index++){
	if($index % $firsNmbr == 0 || $index % $secondNmbr == 0 ){
	array_push($numbers, $index);
	}
}
$sumOfMultiples = array_sum($numbers);
print_r('<b>'.$sumOfMultiples.'</b>');
?>

<h1>Task 2</h1>
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
<br/>
Каждый следующий элемент ряда Фибоначчи получается при сложении двух предыдущих. Начиная с 1 и 2, первые 10 элементов будут:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Найдите сумму всех четных элементов ряда Фибоначчи, которые не превышают четыре миллиона.

<?php

$first = 0;
$second = 1;

$numbers = array();

	
while($next <= 4000000)
{

	$next = $first + $second;
	//echo $next.',';
	$first = $second;
	$second = $next;
	if($next % 2 == 0) {
	array_push($numbers, $next);
	};
	$next++;
}
echo '<br/>Sum of numbers(Variant_1):'.array_sum($numbers);

?>

<?php
$sum = 0;
$fibonacci = 1;
$old1 = 0;
$old2 = 1;

while ($fibonacci <= 4000000) {
	$fibonacci = $old1 + $old2;
	$old1 = $old2;
	$old2 = $fibonacci;
	
	if ($fibonacci % 2 == 0) {
		// it's an even number
		$sum += $fibonacci;
	}
}

echo '<br/>Sum of numbers(Variant_2):'.$sum;
?>
	
</body>
</html>